# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fh-pyinstrument',
                'doc_host': 'https://answerdotai.github.io',
                'git_url': 'https://github.com/answerdotai/fh-pyinstrument',
                'lib_path': 'fh_pyinstrument'},
  'syms': {'fh_pyinstrument.core': {'fh_pyinstrument.core.foo': ('core.html#foo', 'fh_pyinstrument/core.py')}}}
