"""Using pyinstrument to profile FastHTML apps.

Docs: https://answerdotai.github.io/fh-pyinstrument/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ProfileEntry', 'get_trigger_name', 'ProfileMiddleware', 'profiling', 'instrument', 'load_session', 'render_session']

# %% ../nbs/00_core.ipynb #a5f5121f
import os,time,pickle,inspect
from pathlib import Path
from fasthtml.common import *
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.middleware import Middleware
from functools import wraps
from collections import namedtuple
from contextlib import contextmanager
from fastcore.basics import patch
try: from rich import print
except: pass

from pyinstrument import Profiler
from pyinstrument.renderers import ConsoleRenderer, HTMLRenderer
from pyinstrument.session import Session

# %% ../nbs/00_core.ipynb #e776a15d
def get_trigger_name(): return os.environ.get('PYINSTRUMENT_TRIGGER', 'profile')

# %% ../nbs/00_core.ipynb #7a67fec2
class ProfileMiddleware(BaseHTTPMiddleware):
    "Add the power of pyinstrument to potentially every request."
    def __init__(self, app, save_dir=None):
        super().__init__(app)
        self.save_dir = Path(save_dir) if save_dir else None

    def _save(self, profiler):
        if not self.save_dir: return
        self.save_dir.mkdir(parents=True, exist_ok=True)
        with open(self.save_dir/f'{time.time():.0f}.pkl', 'wb') as f: pickle.dump(profiler.last_session, f)

    async def dispatch(self, request, call_next):
        trigger_name = get_trigger_name()
        should_profile = request.query_params.get(trigger_name, False)
        term = request.query_params.get("term", False)
        if should_profile:
            profiler = Profiler()
            profiler.start()
            response = await call_next(request)
            profiler.stop()
            self._save(profiler)
            if term:
                print(profiler.output_text())
                return response
            return HTMLResponse(profiler.output_html())
        return await call_next(request)

# %% ../nbs/00_core.ipynb #a610e1ca
@contextmanager
def profiling():
    p = Profiler()
    p.start()
    try: yield p
    finally: p.stop()

# %% ../nbs/00_core.ipynb #73ea7819
def instrument(route_handler):
    "Replaces the route handler's output with pyinstrument results."
    @wraps(route_handler)
    async def _wrapper(*args, **kwargs):
        with profiling() as p: await maybe_await(route_handler(*args, **kwargs))
        return p.output_html()
    return _wrapper

# %% ../nbs/00_core.ipynb #8adfe620
def load_session(path):
    "Load a saved pyinstrument session and return a renderer-ready object."
    with open(path, 'rb') as f: return pickle.load(f)


# %% ../nbs/00_core.ipynb #23f2c171
ProfileEntry = namedtuple('ProfileEntry', 'time func file line')

def _matches(fp, paths): return not paths or any(p in fp for p in paths)

def _walk_frames(frame, fn, **kwargs):
    fn(frame, **kwargs)
    for c in frame.children: _walk_frames(c, fn, **kwargs)

# %% ../nbs/00_core.ipynb #b5175799
@patch
def flat(self:Session, paths=None, n=20):
    "Aggregate self-time by function, optionally filtered by file path substrings."
    acc = {}
    def _acc(frame):
        fp,st = frame.file_path or '',frame.total_self_time
        if st > 0 and _matches(fp, paths):
            k = (frame.function, fp, frame.line_no)
            acc[k] = acc.get(k, 0) + st
    _walk_frames(self.root_frame(), _acc)
    res = sorted([ProfileEntry(t, f, fp, ln) for (f,fp,ln),t in acc.items()], key=lambda o: -o.time)
    return res[:n]

# %% ../nbs/00_core.ipynb #9bcfbf25
@patch
def callers(self:Session, func_name, paths=None, n=10):
    "Find which functions call `func_name` and how much time they contribute."
    acc = {}
    def _acc(frame, parent=None):
        fp = frame.file_path or ''
        if frame.function == func_name and frame.total_self_time > 0 and parent:
            pfp = parent.file_path or ''
            if _matches(pfp, paths):
                k = (parent.function, pfp, parent.line_no)
                acc[k] = acc.get(k, 0) + frame.total_self_time
        for c in frame.children: _acc(c, parent=frame)
    _acc(self.root_frame())
    res = sorted([ProfileEntry(t, f, fp, ln) for (f,fp,ln),t in acc.items()], key=lambda o: -o.time)
    return res[:n]

# %% ../nbs/00_core.ipynb #cd8bb4cb
@patch
def callees(self:Session, func_name, paths=None, n=10):
    "Find what `func_name` spends its time calling."
    acc = {}
    def _acc(frame, inside=False):
        fp = frame.file_path or ''
        if frame.function == func_name: inside = True
        if inside and frame.total_self_time > 0 and frame.function != func_name and _matches(fp, paths):
            k = (frame.function, fp, frame.line_no)
            acc[k] = acc.get(k, 0) + frame.total_self_time
        for c in frame.children: _acc(c, inside)
    _acc(self.root_frame())
    res = sorted([ProfileEntry(t, f, fp, ln) for (f,fp,ln),t in acc.items()], key=lambda o: -o.time)
    return res[:n]

# %% ../nbs/00_core.ipynb #049ea6b6
@patch
def hot_paths(self:Session, paths=None, n=10, depth=8):
    "Top call stacks by cumulative time, filtered to frames matching `paths`."
    stacks = {}
    def _collect(frame, stack=()):
        fp = frame.file_path or ''
        if _matches(fp, paths): stack = stack + (f"{frame.function} {Path(fp).name}:{frame.line_no}",)
        if frame.total_self_time > 0 and stack:
            trimmed = stack[-depth:]
            stacks[trimmed] = stacks.get(trimmed, 0) + frame.total_self_time
        for c in frame.children: _collect(c, stack)
    _collect(self.root_frame())
    return sorted([(t, ' → '.join(s)) for s,t in stacks.items()], key=lambda o: -o[0])[:n]

# %% ../nbs/00_core.ipynb #d0e08de7
def render_session(sess, text=True, show_all=False, short_mode=True):
    "Render a saved session as text or html."
    if text: return ConsoleRenderer(show_all=show_all, short_mode=short_mode).render(sess)
    return HTMLRenderer(show_all=show_all).render(sess)
