"""Using pyinstrument to profile FastHTML apps."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ProfileMiddleware']

# %% ../nbs/00_core.ipynb 3
from fasthtml.common import *
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.middleware import Middleware
try: from rich import print
except: pass
try:
    from pyinstrument import Profiler
except ImportError:
    raise ImportError('Please install pyinstrument')

# %% ../nbs/00_core.ipynb 4
class ProfileMiddleware(BaseHTTPMiddleware):    
    async def dispatch(self, request, call_next):
        profiling = request.query_params.get("profile", False)
        term = request.query_params.get("term", False)  
        if profiling:
            profiler = Profiler()
            profiler.start()
            response = await call_next(request)            
            profiler.stop()
            if term: 
                print(profiler.output_text())
                return response
            return HTMLResponse(profiler.output_html())
        return await call_next(request)
